export const DELETES_TODO_ITEMS ="DELETES_TODO_ITEMS";
export const ADD_TODO_ITEMS="ADD_TODO_ITEMS";
export const EDITS_TODO_ITEMS="EDITS_TODO_ITEMS";
export const CANCEL_TODO_ITEMS="CANCEL_TODO_ITEMS";
export const CONFIRM_TODO_ITEMS="CONFIRM_TODO_ITEMS";
